name: ack
description: A simple validation library for Dart
version: 0.1.1
repository: https://github.com/leoafarias/ack

environment:
  sdk: ^3.3.0

dependencies:
  meta: ^1.15.0
dev_dependencies:
  coverage: ^1.11.1
  dart_code_metrics_presets: ^2.21.0
  lints: ^5.0.0
  test: ^1.24.0
